//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydromodel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hydromodel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TauDEM {
            get {
                object obj = ResourceManager.GetObject("TauDEM", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p	AreaD8	input
        ///ss	AreaD8	input
        ///wg	AreaD8	input
        ///o	AreaD8	input
        ///ad8	AreaD8	output
        ///ssa	AreaD8	output
        ///ang	AreaDinf	input
        ///wg	AreaDinf	input
        ///o	AreaDinf	input
        ///sca	AreaDinf	output
        ///fel	D8FlowDir	input
        ///p	D8FlowDir	output
        ///sd8	D8FlowDir	output
        ///p	D8FlowPathExtremeUp	input
        ///ssa	D8FlowPathExtremeUp	output
        ///src	D8HDistDown	input
        ///dist	D8HDistDown	output
        ///p	D8HDistToStrm	input
        ///ang	DinfAvalanche	input
        ///ass	DinfAvalanche	input
        ///fel	DinfAvalanche	input
        ///rz	DinfAvalanche	output
        ///dfs	DinfAvalanche 	output
        ///ang	Dinf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string values {
            get {
                return ResourceManager.GetString("values", resourceCulture);
            }
        }
    }
}
